services:
  # Database
  linkinpurry-db:
    container_name: linkinpurry-db
    image: postgres:17
    # image: nicholasliem/wbd-m2-db-image:latest
    env_file:
      - ./backend/.env.docker
    ports:
      - "5436:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - linkinpurry-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}",
        ]

  linkinpurry-redis:
    container_name: linkinpurry-redis
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - linkinpurry-network

  # BE Development (with hot reload)
  linkinpurry-be-dev:
    container_name: linkinpurry-be-dev
    build:
      context: .
      target: development
      dockerfile: ./backend/Dockerfile.run
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app # Mount the backend folder to the container
      - /app/node_modules # Prevent the node_modules folder from being mounted
      - upload-data:/app/public # Upload data
    ports:
      - "3000:3000"
    depends_on:
      - linkinpurry-db
    networks:
      - linkinpurry-network

  # BE Production (no hot reload)
  linkinpurry-be-prod:
    container_name: linkinpurry-be-prod
    build:
      context: .
      target: production
      dockerfile: ./backend/Dockerfile.run
    env_file:
      - ./backend/.env.docker
    volumes:
      - upload-data:/app/public # Upload data
    ports:
      - "3000:3000"
    depends_on:
      - linkinpurry-db
    networks:
      - linkinpurry-network

  # FE development (with hot reload)
  linkinpurry-fe-dev:
    container_name: linkinpurry-fe-dev
    build:
      context: .
      target: development
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./frontend/.env.docker
    volumes:
      - ./frontend:/app # Mount the frontend folder to the container
      - /app/node_modules # Prevent the node_modules folder from being mounted
    ports:
      - "5173:5173"
    networks:
      - linkinpurry-network

  # FE production (no hot reload)
  linkinpurry-fe-prod:
    container_name: linkinpurry-fe-prod
    build:
      context: .
      target: production
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    networks:
      - linkinpurry-network

  # Seeder
  linkinpurry-seeder:
    container_name: linkinpurry-seeder
    build:
      context: .
      target: seeder
      dockerfile: ./backend/Dockerfile.run
    env_file:
      - ./backend/.env.docker
    networks:
      - linkinpurry-network
    depends_on:
      - linkinpurry-db

volumes:
  db-data:
    name: linkinpurry-db-data
  upload-data:
    name: linkinpurry-upload-data

networks:
  linkinpurry-network:
    driver: bridge
