# DOCKER FILE FOR RUNNING THE BACKEND

# Base
FROM node:20-alpine as base
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm ci
COPY ./backend/ ./
RUN npx prisma generate


# For development (nodemon)
FROM base as development
ENV NODE_ENV=development
CMD ["npm" , "run", "dev"]


# For production (run compiled ts (.js) files)
FROM base as production
RUN npm run build
CMD ["npm", "run", "start"]


# Seeder
FROM base as seeder
ENV NODE_ENV=development
CMD ["npm", "run", "seed"]