/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as AuthImport } from './routes/_auth';
import { Route as AuthAuthLoginImport } from './routes/_auth/auth/login';
import { Route as AuthAuthRegisterImport } from './routes/_auth/auth/register';
import { Route as IndexImport } from './routes/index';
import { Route as MyNetworksUserIdImport } from './routes/my-networks/$userId';
import { Route as MyNetworksConnectinRequestUserIdImport } from './routes/my-networks/connectin-request/$userId';
import { Route as UsersUserIdImport } from './routes/users/$userId';

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const UsersUserIdRoute = UsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any);

const MyNetworksUserIdRoute = MyNetworksUserIdImport.update({
  id: '/my-networks/$userId',
  path: '/my-networks/$userId',
  getParentRoute: () => rootRoute,
} as any);

const MyNetworksConnectinRequestUserIdRoute = MyNetworksConnectinRequestUserIdImport.update({
  id: '/my-networks/connectin-request/$userId',
  path: '/my-networks/connectin-request/$userId',
  getParentRoute: () => rootRoute,
} as any);

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any);

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/my-networks/$userId': {
      id: '/my-networks/$userId';
      path: '/my-networks/$userId';
      fullPath: '/my-networks/$userId';
      preLoaderRoute: typeof MyNetworksUserIdImport;
      parentRoute: typeof rootRoute;
    };
    '/users/$userId': {
      id: '/users/$userId';
      path: '/users/$userId';
      fullPath: '/users/$userId';
      preLoaderRoute: typeof UsersUserIdImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/auth/login': {
      id: '/_auth/auth/login';
      path: '/auth/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthAuthLoginImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/auth/register': {
      id: '/_auth/auth/register';
      path: '/auth/register';
      fullPath: '/auth/register';
      preLoaderRoute: typeof AuthAuthRegisterImport;
      parentRoute: typeof AuthImport;
    };
    '/my-networks/connectin-request/$userId': {
      id: '/my-networks/connectin-request/$userId';
      path: '/my-networks/connectin-request/$userId';
      fullPath: '/my-networks/connectin-request/$userId';
      preLoaderRoute: typeof MyNetworksConnectinRequestUserIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute;
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/my-networks/$userId': typeof MyNetworksUserIdRoute;
  '/users/$userId': typeof UsersUserIdRoute;
  '/auth/login': typeof AuthAuthLoginRoute;
  '/auth/register': typeof AuthAuthRegisterRoute;
  '/my-networks/connectin-request/$userId': typeof MyNetworksConnectinRequestUserIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/my-networks/$userId': typeof MyNetworksUserIdRoute;
  '/users/$userId': typeof UsersUserIdRoute;
  '/auth/login': typeof AuthAuthLoginRoute;
  '/auth/register': typeof AuthAuthRegisterRoute;
  '/my-networks/connectin-request/$userId': typeof MyNetworksConnectinRequestUserIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/my-networks/$userId': typeof MyNetworksUserIdRoute;
  '/users/$userId': typeof UsersUserIdRoute;
  '/_auth/auth/login': typeof AuthAuthLoginRoute;
  '/_auth/auth/register': typeof AuthAuthRegisterRoute;
  '/my-networks/connectin-request/$userId': typeof MyNetworksConnectinRequestUserIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '' | '/my-networks/$userId' | '/users/$userId' | '/auth/login' | '/auth/register' | '/my-networks/connectin-request/$userId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '' | '/my-networks/$userId' | '/users/$userId' | '/auth/login' | '/auth/register' | '/my-networks/connectin-request/$userId';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/my-networks/$userId'
    | '/users/$userId'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/my-networks/connectin-request/$userId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  MyNetworksUserIdRoute: typeof MyNetworksUserIdRoute;
  UsersUserIdRoute: typeof UsersUserIdRoute;
  MyNetworksConnectinRequestUserIdRoute: typeof MyNetworksConnectinRequestUserIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MyNetworksUserIdRoute: MyNetworksUserIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  MyNetworksConnectinRequestUserIdRoute: MyNetworksConnectinRequestUserIdRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/my-networks/$userId",
        "/users/$userId",
        "/my-networks/connectin-request/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth/login",
        "/_auth/auth/register"
      ]
    },
    "/my-networks/$userId": {
      "filePath": "my-networks/$userId.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    },
    "/_auth/auth/login": {
      "filePath": "_auth/auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/register": {
      "filePath": "_auth/auth/register.tsx",
      "parent": "/_auth"
    },
    "/my-networks/connectin-request/$userId": {
      "filePath": "my-networks/connectin-request/$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
